services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mgs
      POSTGRES_PASSWORD: mgs_local
      POSTGRES_DB: mgs_clients
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
